name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper for Artifact Registry
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    # Optional: This step should only run once (or when needed), you may skip it if the repository is already created.
    - name: Create Artifact Registry repository
      run: |
        gcloud artifacts repositories create secureprint-backend --repository-format=docker \
        --location=asia-south1 --description="Docker repository for secureprint backend" --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image to Artifact Registry
      run: |
        cd backend
        docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secureprint-backend/secureprint-backend:${{ github.sha }} .
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secureprint-backend/secureprint-backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy secureprint-backend-south \
          --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secureprint-backend/secureprint-backend:${{ github.sha }} \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated \
          --project=${{ secrets.GCP_PROJECT_ID }}
