name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image to Artifact Registry
      run: |
        cd backend
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secureprint-backend/secureprint-backend:${{ github.sha }} .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secureprint-backend/secureprint-backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy secureprint-backend \
          --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/secureprint-backend/secureprint-backend:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
